language: c
compiler:
  - gcc
  - clang
  - tcc
  - x86_64-w64-mingw32-gcc
  - i686-w64-mingw32-gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq wine gcc-mingw-w64-i686 binutils-mingw-w64-i686 gcc-mingw-w64-x86-64 binutils-mingw-w64-x86-64 tcc
script: cd test && ./check.sh
